name: "Switch matrix"
description: "Run heterogeneous commands in a GitHub workflow job matrix"
author: Jakob Lilliemarck

inputs:
  key:
    description: "The current key"
    required: true

  instruction:
    description: |
      Multiline string with a key, cmd pair on each line, like:
        key=foo,cmd=echo foo
        key=bar,cmd=echo bar
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
